### ISSUE TITLE
How to configure more buttons

### ISSUE THREAD

**Issue by DAVIZINH0** [loick111/dash-domoticz#1]
Hello, and sorry for this issue because is not a issue :-(
Your docker are very usefull for me and i use it in synology perfectly
But i have a noob problem. 
I configure one button with this yaml.

> # button.yml
default:
   lights:
    name: Fairy
    addr: xc:xx:xx:xx:xb:xx
    toggle: [307]

but i dont know how to configure more buttons. I have 4 dash buttons.
Can you help me?
thanks a lot!

**Comment by loick111** [comment]
Hello!

You can add multiple blocks in the YAML config file in `default`.
Here is an example of `button.yml` with two lights:
```yaml
default:
  l1:
    name: TV Lights
    addr: xx:xx:xx:xx:xx:xx
    toggle: [1, 2, 3]
  l2:
    name: Light 2
    addr: xx:xx:xx:xx:xx:xx
    toggle: [404]
```

I hope this will help you ;)
